"""
Django settings for mywebsite project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import sentry_sdk
import structlog
from decouple import AutoConfig, Choices
from sentry_sdk.integrations.logging import LoggingIntegration
from structlog_sentry import SentryProcessor

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loading `.env` files
# See docs: https://github.com/HBNetwork/python-decouple
config = AutoConfig(search_path=BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

SECRET_KEY = config('DJANGO_SECRET_KEY')

DEBUG = config('DJANGO_ENV', default='production') == 'debug'

ALLOWED_HOSTS = [
                    'localhost',
                    '0.0.0.0',  # noqa: S104
                    '127.0.0.1',
                    '[::1]',
                ] + config(
    'ALLOWED_HOSTS',
    default='',
).split(',')

INSTALLED_APPS = [
    'daphne',  # asgi and websockets support for channels lib
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jsoneditor',
    'account',
    'chat',
    'main',
    'payments',
]

ASGI_APPLICATION = 'mywebsite.asgi.application'

CHANNEL_LAYERS_BACKEND = config(
    'CHANNEL_LAYERS_BACKEND',
    cast=Choices(['redis', 'inmemory']),
)
if CHANNEL_LAYERS_BACKEND == 'inmemory':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
if CHANNEL_LAYERS_BACKEND == 'redis':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer',
            'CONFIG': {
                'hosts': [
                    (
                        config('REDIS_HOST', default='localhost'),
                        config('REDIS_PORT', cast=int, default=6379),
                    ),
                ],
            },
        },
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mywebsite.timezone_middleware.TimeZoneMiddleware',
]

ROOT_URLCONF = 'mywebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mywebsite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('DJANGO_DATABASE_HOST'),
        'PORT': config('DJANGO_DATABASE_PORT', cast=int),
        'CONN_MAX_AGE': config('CONN_MAX_AGE', cast=int, default=60),
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=15000ms',
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

_PASS = 'django.contrib.auth.password_validation'  # noqa: S105
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': f'{_PASS}.UserAttributeSimilarityValidator'},
    {'NAME': f'{_PASS}.MinimumLengthValidator'},
    {'NAME': f'{_PASS}.CommonPasswordValidator'},
    {'NAME': f'{_PASS}.NumericPasswordValidator'},
]

# S113 requires to set timeut for get/post requests
# https://requests.readthedocs.io/en/latest/user/advanced/#timeouts
REQUESTS_TIMEOUT = (3.05, 27)

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

HOST = config('HOST', default='http://localhost:8000/')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR.joinpath('static')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.joinpath('media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django authentication system
# https://docs.djangoproject.com/en/3.2/topics/auth/
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

if DEBUG:
    # Disable persistent DB connections
    # https://docs.djangoproject.com/en/3.2/ref/databases/#caveats
    DATABASES['default']['CONN_MAX_AGE'] = 0

# Security
# https://docs.djangoproject.com/en/3.2/topics/security/

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

X_FRAME_OPTIONS = 'DENY'

# https://docs.djangoproject.com/en/4.1/ref/middleware/#referrer-policy
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
SECURE_REFERRER_POLICY = 'same-origin'

USE_HTTPS = config('USE_HTTPS', cast=bool, default=False)

if USE_HTTPS:
    # Security
    # https://docs.djangoproject.com/en/3.2/topics/security/

    SECURE_HSTS_SECONDS = 31536000  # the same as Caddy has
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = [
        # This is required for healthcheck to work:
        '^health/',
    ]

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

shared_structlog_processors = [
    structlog.contextvars.merge_contextvars,
    structlog.processors.TimeStamper(fmt='iso'),
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.StackInfoRenderer(),
    structlog.processors.UnicodeDecoder(),
    SentryProcessor(
        tag_keys=['logger', 'level'],
    ),
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.dev.ConsoleRenderer(),
            'foreign_pre_chain': shared_structlog_processors,
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['console'],
            'propagate': False,
            'level': 'WARN',
        },
        'django.channels.server': {
            'handlers': ['console'],
            'propagate': False,
            'level': 'WARN',
        },
        'django': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'WARN',
        },
        'security': {
            'handlers': ['console'],
            'level': 'WARN',
            'propagate': False,
        },
    },
}

if not structlog.is_configured():
    structlog.configure(
        processors=shared_structlog_processors
                   + [
                       structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
                   ],
        logger_factory=structlog.stdlib.LoggerFactory(),
        cache_logger_on_first_use=True,
    )

SMS_TRANSPORT = config('SMS_TRANSPORT', default='stub')
SMS_API_KEY = config('SMS_API_KEY', default=None)

INFLUXDB_V2_URL = config('INFLUXDB_V2_URL', default='http://localhost:8086')
INFLUXDB_V2_ORG = config('INFLUXDB_V2_ORG', default='eco-nrg')
INFLUXDB_V2_TOKEN = config('INFLUXDB_V2_TOKEN', default='CHANGE_ME')

INFLUXDB_MIDDLEWARE_DISABLED = config(
    'INFLUXDB_MIDDLEWARE_DISABLED',
    cast=bool,
    default=True,
)
INFLUXDB_MIDDLEWARE_BUCKET = config('INFLUXDB_MIDDLEWARE_BUCKET', default='api')

if config('SENTRY_DSN', '') != '':
    sentry_sdk.init(
        dsn=config('SENTRY_DSN'),
        environment=config('SENTRY_ENV', 'local'),
        integrations=[
            # Не отправляем на sentry стандартные логи,
            # так как их отправляет сам structlog.SentryProcessor
            LoggingIntegration(event_level=None, level=None),
        ],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production,
        traces_sample_rate=0,
    )

PAYMENT_ENABLED = config('PAYMENT_ENABLED', default=False, cast=bool)
ALFA_BASE_URL = config('ALFA_BASE_URL')
ALFA_REGISTER_PAYMENT = config('ALFA_REGISTER_PAYMENT')
ALFA_GET_PAYMENT = config('ALFA_GET_PAYMENT')
ALFA_GET_SBP_LINK = config('ALFA_GET_SBP_LINK')
ALFA_API_USERNAME = config('ALFA_API_USERNAME')
ALFA_API_PASSWORD = config('ALFA_API_PASSWORD')
ALFA_WEBHOOK_SECRET_KEY = config('ALFA_WEBHOOK_SECRET_KEY')
ALFA_RETURN_URL = config('ALFA_RETURN_URL')
ALFA_FAIL_URL = config('ALFA_FAIL_URL')
CURRENCY = config('CURRENCY', default=643, cast=int)
ALFA_LANGUAGE = config('ALFA_LANGUAGE', default='ru')
MINIMUM_PAYMENT = config('MINIMUM_PAYMENT', default=1.0, cast=float)
MAXIMUM_PAYMENT = config('MAXIMUM_PAYMENT', default=500000.0, cast=float)
CARD_COMMISSION = config('CARD_COMMISSION', default=1.03, cast=float)

LESS_BALANCE = config('LESS_BALANCE', default=100.0, cast=float)
RECOMMENDED_BALANCE = config('RECOMMENDED_BALANCE', default=1000.0, cast=float)

DEFAULT_FREE_HOURS = config('DEFAULT_FREE_HOURS', default=10.0, cast=float)

REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)

FRONTEND_BASE_URL = config('FRONTEND_BASE_URL', default='https://charge.eco-nrg.store')
PAYMENT_PAGE = config('PAYMENT_PAGE', default='/payment')
STATION_ACTIVATION = config('STATION_ACTIVATION', default='/spaces?id=')
