# Generated by Django 3.0.5 on 2021-11-04 21:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_id",
                    models.BigIntegerField(null=True, verbose_name="Связанный объект"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("SU", "Регистрация"),
                            ("D", "Пополнение"),
                            ("B", "Покупка"),
                            ("MB", "Возрат денег"),
                        ],
                        max_length=3,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "rubles",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=19,
                        verbose_name="Рублей",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Завершен"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен",
                "verbose_name_plural": "Токены",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("car_manufacturer", models.CharField(blank=True, max_length=50)),
                ("car_model", models.CharField(blank=True, max_length=50)),
                (
                    "car_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Номер машины",
                    ),
                ),
                (
                    "rubles",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=19,
                        verbose_name="Рублей",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(default=0, verbose_name="Рейтинг"),
                ),
                (
                    "can_charge_free",
                    models.BooleanField(
                        default=True,
                        verbose_name="Может заряжаться бесплатно",
                    ),
                ),
                (
                    "free_seconds",
                    models.PositiveIntegerField(
                        default=10800,
                        verbose_name="Бесплатных секунд",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="000000",
                        max_length=6,
                        verbose_name="Код входа",
                    ),
                ),
                ("last_code_sent", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Сохранен"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
