# Generated by Django 3.0.5 on 2021-12-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="battery_power",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Емкость батареи",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="car_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Год выпуска",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="fast_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHADEMO", "CHADEMO"),
                    ("CCS-Combo1", "CCS-Combo1"),
                    ("CCS-Combo2", "CCS-Combo2"),
                    ("GB-T", "GB-T"),
                ],
                max_length=15,
                null=True,
                verbose_name="Быстрый тип",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Отчество"),
        ),
        migrations.AddField(
            model_name="profile",
            name="slow_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("J1772", "TYPE1 (J1772)"),
                    ("IEC62196", "TYPE2 (IEC62196)"),
                    ("TESLA_US", "TESLA US"),
                ],
                max_length=15,
                null=True,
                verbose_name="Медленный тип",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="car_manufacturer",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Марка машины",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="car_model",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Модель машин",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Имя"),
        ),
    ]
