# Generated by Django 3.1.4 on 2023-01-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
    ]
