# Generated by Django 3.1.4 on 2023-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='Профиль заполнен'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='free_seconds',
            field=models.PositiveIntegerField(
                default=18000,
                verbose_name='Бесплатных секунд',
            ),
        ),
    ]
