# Generated by Django 4.2 on 2023-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_auto_20230315_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
    ]
