# Generated by Django 4.2 on 2023-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0007_alter_connection_id_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_book',
            field=models.BooleanField(default=True, verbose_name='Может бронировать'),
        ),
    ]
