# Generated by Django 4.2.2 on 2023-08-16 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0008_profile_can_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rubles',
        ),
    ]
