# Generated by Django 4.2.2 on 2023-08-16 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0009_remove_profile_rubles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
