# Generated by Django 4.2.5 on 2023-09-05 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0010_delete_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
