# Generated by Django 4.2.5 on 2024-02-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0011_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='free_seconds',
            field=models.PositiveIntegerField(
                default=36000.0, verbose_name='Бесплатных секунд'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slow_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('J1772', 'TYPE1 (J1772)'),
                    ('IEC62196', 'TYPE2 (IEC62196)'),
                    ('TESLA_US', 'TESLA US'),
                    ('GB_T_AC', 'GB/T (AC)'),
                ],
                max_length=15,
                null=True,
                verbose_name='Медленный тип',
            ),
        ),
    ]
