# Generated by Django 4.2.5 on 2024-05-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0012_add_new_connector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trial_time',
            field=models.PositiveBigIntegerField(
                default=0, verbose_name='Бесплатное время зарядки'
            ),
        ),
    ]
