# Generated by Django 4.2.5 on 2024-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0013_add_trial_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name='Электронная почта'
            ),
        ),
    ]
