# Generated by Django 3.0.5 on 2021-11-04 21:03

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("ip", models.CharField(max_length=15, verbose_name="IP адрес")),
                (
                    "rtsp_url",
                    models.CharField(
                        default="/",
                        help_text="Начиная со слэша",
                        max_length=255,
                        verbose_name="RTSP URL",
                    ),
                ),
                ("image", models.ImageField(upload_to=main.models.get_image_path)),
                ("image_iter", models.SmallIntegerField(default=0)),
                ("last_image_update", models.DateTimeField(auto_now_add=True)),
                ("order_index", models.IntegerField(verbose_name="Индекс сортировки")),
            ],
            options={
                "verbose_name": "Камера",
                "verbose_name_plural": "Камеры",
                "ordering": ("-order_index",),
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(max_length=50, unique=True, verbose_name="UID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "red_pin_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Номер пина красного диода",
                    ),
                ),
                (
                    "green_pin_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Номер пина зеленого диода",
                    ),
                ),
                (
                    "blue_pin_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Номер пина синего диода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заправка",
                "verbose_name_plural": "Заправки",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[("TES_US", "Tesla USA"), ("TES_EU", "Tesla EU")],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "uid",
                    models.CharField(max_length=50, unique=True, verbose_name="UID"),
                ),
                (
                    "price_kw",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена за кВт",
                    ),
                ),
                (
                    "price_hour",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена за час стоянки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DI", "Свободно"),
                            ("BU", "Занято"),
                            ("DI", "Отключено"),
                        ],
                        max_length=5,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_kw",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=19,
                        verbose_name="Накопленная энергия",
                    ),
                ),
                (
                    "current_w",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Текущее значение мощности",
                    ),
                ),
                (
                    "current_v",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Текущее значение напряжения",
                    ),
                ),
                (
                    "current_a",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Текущее значение тока",
                    ),
                ),
                (
                    "is_on",
                    models.BooleanField(default=False, verbose_name="Счетчик включен"),
                ),
                ("last_data_update", models.DateTimeField(auto_now_add=True)),
                (
                    "parklock_mac",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        verbose_name="MAC адрес парклока",
                    ),
                ),
                (
                    "meter_com_port",
                    models.IntegerField(verbose_name="COM порт счетчика"),
                ),
                (
                    "meter_code",
                    models.IntegerField(
                        help_text="Код авторизации",
                        verbose_name="Серийный номер счетчика",
                    ),
                ),
                (
                    "relay_pin_number",
                    models.IntegerField(blank=True, null=True, verbose_name="Пин реле"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="main.ParkingLot",
                        verbose_name="Парковка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="SmsSend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Текст")),
                ("JSON_result", models.TextField(verbose_name="Результат")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Отправка СМС",
                "verbose_name_plural": "Отправки СМС",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ParkingSpaceStat",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DI", "Свободно"),
                            ("BU", "Занято"),
                            ("DI", "Отключено"),
                        ],
                        max_length=5,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_kw",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=19,
                        verbose_name="Накопленная энергия",
                    ),
                ),
                (
                    "current_w",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Текущее значение мощности",
                    ),
                ),
                (
                    "current_v",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Текущее значение напряжения",
                    ),
                ),
                (
                    "current_a",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Текущее значение тока",
                    ),
                ),
                (
                    "is_on",
                    models.BooleanField(default=False, verbose_name="Счетчик включен"),
                ),
                ("last_data_update", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.ParkingSpace",
                        verbose_name="Парковочное место",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика места",
                "verbose_name_plural": "Статистика мест",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ParkingSpaceConnector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("IEC_62196", "IEC 62196"),
                            ("J1772", "J1772"),
                            ("TES_US", "Tesla Us"),
                        ],
                        max_length=20,
                        verbose_name="Тип разъема",
                    ),
                ),
                ("phases_count", models.SmallIntegerField(verbose_name="Кол-во фаз")),
                (
                    "max_kw",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Максимальная мощность, кВт",
                    ),
                ),
                (
                    "max_a",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Максимальный ток, А",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="main.ParkingSpace",
                        verbose_name="Парковочное место",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коннектор места",
                "verbose_name_plural": "Коннекторы мест",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Активен"),
                            ("NOM", "Без оплаты"),
                            ("FIN", "Завершен"),
                        ],
                        max_length=5,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "start_kw",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=19,
                        verbose_name="Начальная накопленная энергия",
                    ),
                ),
                (
                    "end_kw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        null=True,
                        verbose_name="Конечная накопленная энергия",
                    ),
                ),
                (
                    "last_kw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        null=True,
                        verbose_name="Последняя обработанная накопленная энергия",
                    ),
                ),
                (
                    "last_process_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Время последней обработки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(null=True, verbose_name="Завершен"),
                ),
                (
                    "total_rubles",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=19,
                        verbose_name="Рублей",
                    ),
                ),
                (
                    "payload",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=main.models.get_empty_dict,
                        editable=False,
                        verbose_name="Дополнительные поля",
                    ),
                ),
                (
                    "connector_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="main.ParkingSpaceConnector",
                        verbose_name="Выбранный коннектор",
                    ),
                ),
                (
                    "selected_camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.Camera",
                        verbose_name="Выбранная камера",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="main.ParkingSpace",
                        verbose_name="Парковочное место",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="main.ParkingLot",
                        verbose_name="Парковка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(editable=False, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citys",
                        to="main.Country",
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ("-pk",),
            },
        ),
        migrations.AddField(
            model_name="camera",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cameras",
                to="main.ParkingLot",
                verbose_name="Парковка",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="space",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.ParkingSpace",
                verbose_name="Парковочное место",
            ),
        ),
    ]
