# Generated by Django 3.0.5 on 2021-11-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspace",
            name="meter_com_port",
            field=models.CharField(max_length=20, verbose_name="COM порт счетчика"),
        ),
    ]
