# Generated by Django 3.0.5 on 2021-11-04 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_auto_20211105_0010"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="created_at",
        ),
        migrations.AddField(
            model_name="device",
            name="name",
            field=models.CharField(
                default="TEST",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="main.ParkingLot",
                verbose_name="Парковка",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="selected_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.Camera",
                verbose_name="Выбранная камера",
            ),
        ),
    ]
