# Generated by Django 3.0.5 on 2021-11-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_auto_20211105_0019"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspace",
            name="relay_pin_number",
        ),
        migrations.AddField(
            model_name="parkingspaceconnector",
            name="relay_pin_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="Пин реле"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="rtsp_url",
            field=models.CharField(
                help_text="Полный URL подключения",
                max_length=255,
                verbose_name="RTSP URL",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="status",
            field=models.CharField(
                choices=[("AW", "Свободно"), ("BU", "Занято"), ("DI", "Отключено")],
                max_length=5,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspacestat",
            name="status",
            field=models.CharField(
                choices=[("AW", "Свободно"), ("BU", "Занято"), ("DI", "Отключено")],
                max_length=5,
                verbose_name="Статус",
            ),
        ),
    ]
