# Generated by Django 3.0.5 on 2021-12-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_auto_20211106_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="start_payed",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Время начала платной зарядки",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.ParkingSpace",
                verbose_name="Парковочное место",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Завершен"),
        ),
    ]
