# Generated by Django 3.0.5 on 2021-12-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_auto_20211217_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payed_kw",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                editable=False,
                max_digits=19,
                verbose_name="Платных киловатт",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payed_seconds",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                editable=False,
                max_digits=19,
                verbose_name="Платное время",
            ),
        ),
    ]
