# Generated by Django 3.0.5 on 2021-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_auto_20211217_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payed_kw",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                editable=False,
                max_digits=19,
                verbose_name="Платных киловатт",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payed_seconds",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=19,
                verbose_name="Платное время",
            ),
        ),
    ]
