# Generated by Django 3.0.5 on 2021-12-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_auto_20211217_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspace",
            name="current_a",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Текущее значение тока",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="current_v",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Текущее значение напряжения",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="current_w",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Текущее значение мощности",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="total_kw",
            field=models.DecimalField(
                decimal_places=3,
                editable=False,
                max_digits=19,
                verbose_name="Накопленная энергия",
            ),
        ),
    ]
