# Generated by Django 3.2.12 on 2022-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_auto_20220411_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglot",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="current_a",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="Текущее значение тока",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="current_v",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="Текущее значение напряжения",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="current_w",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="Текущее значение мощности",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="total_kw",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                editable=False,
                max_digits=19,
                verbose_name="Накопленная энергия",
            ),
        ),
    ]
