# Generated by Django 3.2.12 on 2022-06-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_auto_20220609_2300"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="country",
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="main.city",
                verbose_name="Город",
            ),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
