# Generated by Django 4.1.2 on 2022-10-09 21:50

from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_auto_20220616_2251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payload",
            field=models.JSONField(
                default=main.models.get_empty_dict,
                editable=False,
                verbose_name="Дополнительные поля",
            ),
        ),
    ]
