# Generated by Django 3.1.4 on 2023-03-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0012_alter_order_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='blue_pin_number',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='green_pin_number',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='red_pin_number',
        ),
        migrations.AddField(
            model_name='device',
            name='space',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='devices',
                to='main.parkingspace',
                verbose_name='Место',
            ),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='zoom',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Масштаб'),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='active_amp',
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text='Ампер',
                verbose_name='Уровень тока активной зарядки',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='blue_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина синего диода',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='green_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина зеленого диода',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='meter_model',
            field=models.CharField(
                choices=[
                    ('M_234_ART_02_POR', 'Меркурий 234 ART-01 POR (старый)'),
                    ('M_234_ART_02_POR', 'Меркурий 234 ARTM2-02 POBR.R'),
                ],
                default='M_234_ART_02_POR',
                max_length=255,
                verbose_name='Модель счетчика',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='parklock_com_port',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name='COM порт парклока',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='parklock_led_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина диода парклока',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='red_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина красного диода',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='reed_switch_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина геркона',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='sonic_car_distance',
            field=models.FloatField(default=100, verbose_name='Расстояние до машины'),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='sonic_echo_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина триггера парктроника',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='sonic_floor_distance',
            field=models.FloatField(default=250, verbose_name='Расстояние до земли'),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='sonic_led_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина диода парктроника',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='sonic_trigger_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина триггера парктроника',
            ),
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='meter_com_port',
            field=models.CharField(max_length=40, verbose_name='COM порт счетчика'),
        ),
        migrations.AlterField(
            model_name='parkingspaceconnector',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='smssend',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
    ]
