# Generated by Django 3.1.4 on 2023-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0013_auto_20230303_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                max_digits=18,
                null=True,
                verbose_name='Широта',
            ),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                max_digits=18,
                null=True,
                verbose_name='Долгота',
            ),
        ),
    ]
