# Generated by Django 3.1.4 on 2023-03-15 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20230303_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='map_image',
            field=models.ImageField(
                default='static/map/1/jpg',
                help_text='300 x 400 px',
                upload_to=main.models.get_map_path,
                verbose_name='Изобажение карты',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='parklock_type',
            field=models.CharField(
                choices=[('qh.com.parkinglock', 'Новый qh.com.parkinglock')],
                default='ttlock',
                max_length=255,
                verbose_name='Тип парклока',
            ),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='meter_model',
            field=models.CharField(
                choices=[
                    ('M_234_ART_02_POR', 'Меркурий 234 ART-01 POR (старый)'),
                    ('M_234_ARTM2_02_POBR_R', 'Меркурий 234 ARTM2-02 POBR.R'),
                ],
                default='M_234_ART_02_POR',
                max_length=255,
                verbose_name='Модель счетчика',
            ),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='sonic_echo_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина эхо парктроника',
            ),
        ),
        migrations.CreateModel(
            name='SpaceNotification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
                ),
                (
                    'space',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to='main.parkingspace',
                        verbose_name='Парковочное место',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Уведомление об освобождении',
                'verbose_name_plural': 'Уведомления об освобождении',
            },
        ),
    ]
