# Generated by Django 3.1.4 on 2023-03-17 14:12

import django.db.models.deletion
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0015_auto_20230315_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='send_by_space',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='send_space_cameras',
                to='main.parkingspace',
                verbose_name='Отправлять общий вид с этого устройства',
            ),
        ),
        migrations.AlterField(
            model_name='camera',
            name='space',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cameras',
                to='main.parkingspace',
                verbose_name='Парковочное место',
            ),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='map_image',
            field=models.ImageField(
                default='map/1.jpg',
                help_text='300 x 400 px',
                upload_to=main.models.get_map_path,
                verbose_name='Изобажение карты',
            ),
        ),
    ]
