# Generated by Django 4.2 on 2023-05-31 10:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_alter_camera_id_alter_city_id_alter_parkinglot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspacestat',
            name='space',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stats',
                to='main.parkingspace',
                verbose_name='Парковочное место',
            ),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(verbose_name='Время создания')),
                ('booked_until', models.DateTimeField(verbose_name='Забронировано до')),
                (
                    'activated_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Время активации',
                    ),
                ),
                (
                    'cancelled_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Время отмены',
                    ),
                ),
                (
                    'connector',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bookings',
                        to='main.parkingspaceconnector',
                        verbose_name='Выбранный коннектор',
                    ),
                ),
                (
                    'order',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='booking',
                        to='main.order',
                        verbose_name='Активированный заказ',
                    ),
                ),
                (
                    'space',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bookings',
                        to='main.parkingspace',
                        verbose_name='Парковочное место',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bookings',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ('-created_at',),
            },
        ),
    ]
