# Generated by Django 4.2 on 2023-05-31 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_alter_parkingspacestat_space_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='is_occupied',
            field=models.BooleanField(
                default=False,
                verbose_name="Парковка занята машиной",
            ),
        ),
        migrations.AddField(
            model_name='parkingspacestat',
            name='is_occupied',
            field=models.BooleanField(
                default=False,
                verbose_name="Парковка занята машиной",
            ),
        ),
    ]
