# Generated by Django 4.2.2 on 2023-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'main',
            '0019_alter_parkingspace_add_is_occupied_alter_parkingspacestat_add_is_occupied',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='is_manually_disabled',
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name='Станция выключена администратором',
            ),
        ),
    ]
