# Generated by Django 4.2.2 on 2023-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0020_parkingspace_is_manually_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='parklock_status_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Номер пина для получение статуса парклока',
            ),
        ),
    ]
