# Generated by Django 4.2.2 on 2023-08-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0021_parkingspace_parklock_status_pin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                max_digits=18,
                null=True,
                verbose_name='Широта',
            ),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                max_digits=18,
                null=True,
                verbose_name='Долгота',
            ),
        ),
        migrations.AddField(
            model_name='city',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Масштаб'),
        ),
    ]
