# Generated by Django 4.2.2 on 2023-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0022_city_latitude_city_longitude_city_map_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='mode',
            field=models.CharField(
                choices=[('PROD', 'Боевая'), ('TEST', 'Тестовая')],
                default='TEST',
                max_length=10,
                verbose_name='Режим работы',
            ),
        ),
    ]
