# Generated by Django 4.2.2 on 2023-08-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0023_parkingspace_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(
                choices=[
                    ('AW', 'Свободно'),
                    ('BU', 'Занято'),
                    ('DI', 'Отключено'),
                    ('BO', 'Забронировано'),
                ],
                max_length=5,
                verbose_name='Статус',
            ),
        ),
        migrations.AlterField(
            model_name='parkingspacestat',
            name='status',
            field=models.CharField(
                choices=[
                    ('AW', 'Свободно'),
                    ('BU', 'Занято'),
                    ('DI', 'Отключено'),
                    ('BO', 'Забронировано'),
                ],
                max_length=5,
                verbose_name='Статус',
            ),
        ),
    ]
