# Generated by Django 4.2.5 on 2023-09-05 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0024_alter_parkingspace_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpaceNotification',
        ),
    ]
