# Generated by Django 4.2.5 on 2023-09-07 07:10

import django.db.models.deletion
from django.db import migrations, models


def insert_data(apps, schema_editor):
    provider = apps.get_model('main', 'Provider')

    # Insert data
    provider.objects.create(
        name='ЭКО-ЭНЕРГО',
        address='350020, Краснодарский край, г Краснодар, ул Коммунаров, д. 221/1, офис 16',
        ogrn='1222300026167',
        inn='2310228986',
        kpp='231001001',
        payment_account='',
        branch_office='',
        pao='',
        bik='',
        correspondent_account='',
        extra_information={'email': 'info@eco-nrg.stor'},
    )


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0025_delete_spacenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=256,
                        verbose_name='Общество с ограниченной ответственностью',
                    ),
                ),
                (
                    'address',
                    models.CharField(verbose_name='Юридический и фактический адрес'),
                ),
                ('ogrn', models.CharField(max_length=16, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=16, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=16, verbose_name='КПП')),
                (
                    'payment_account',
                    models.CharField(max_length=32, verbose_name='Расчетный счет'),
                ),
                (
                    'branch_office',
                    models.CharField(blank=True, max_length=64, verbose_name='Филиал'),
                ),
                ('pao', models.CharField(verbose_name='ПАО')),
                ('bik', models.CharField(max_length=16, verbose_name='БИК')),
                (
                    'correspondent_account',
                    models.CharField(verbose_name='Корреспондентский счет'),
                ),
                (
                    'extra_information',
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name='Дополнительная информация по провайдеру',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Провайдер',
                'verbose_name_plural': 'Провайдеры',
            },
        ),
        migrations.CreateModel(
            name='ProviderParkingLot',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'provider_type',
                    models.CharField(
                        choices=[
                            ('PROVIDING', 'Организация предоставляющая услуги'),
                            ('SERVICE', 'Обслуживающая организация'),
                        ],
                        max_length=20,
                        verbose_name='Тип провайдера',
                    ),
                ),
                (
                    'parking_lot',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='main.parkinglot',
                        verbose_name='Парковка',
                    ),
                ),
                (
                    'providers',
                    models.ManyToManyField(
                        related_name='parking_relationships',
                        to='main.provider',
                        verbose_name='Провайдеры',
                    ),
                ),
            ],
            options={
                'verbose_name': 'провайдера для парковочного места',
                'verbose_name_plural': 'Провайдеры для парковочного места',
                'unique_together': {('parking_lot', 'provider_type')},
            },
        ),
        migrations.RunPython(insert_data),
    ]
