# Generated by Django 4.2.5 on 2023-09-26 10:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0026_provider_providerparkinglot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_rubles',
        ),
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                max_digits=19,
                verbose_name='Стоимость бронирования',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='cost_kw',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                max_digits=19,
                verbose_name='Стоимость кВт',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='cost_time',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                max_digits=19,
                verbose_name='Стоимость за простой',
            ),
        ),
    ]
