# Generated by Django 4.2.5 on 2023-10-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0027_remove_order_payload_remove_order_total_rubles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(
                blank=True, verbose_name='Юридический и фактический адрес'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='bik',
            field=models.CharField(blank=True, max_length=16, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='correspondent_account',
            field=models.CharField(blank=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='inn',
            field=models.CharField(blank=True, max_length=16, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='kpp',
            field=models.CharField(blank=True, max_length=16, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ogrn',
            field=models.CharField(blank=True, max_length=16, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='pao',
            field=models.CharField(blank=True, verbose_name='ПАО'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='payment_account',
            field=models.CharField(
                blank=True, max_length=32, verbose_name='Расчетный счет'
            ),
        ),
    ]
