# Generated by Django 4.2.5 on 2023-11-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0028_alter_provider_address_alter_provider_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='meter_code',
            field=models.PositiveIntegerField(
                help_text='Код авторизации', verbose_name='Серийный номер счетчика'
            ),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='meter_model',
            field=models.CharField(
                choices=[
                    ('M_234_ART_02_POR', 'Меркурий 234 ART-01 POR (старый)'),
                    ('M_234_ARTM2_02_POBR_R', 'Меркурий 234 ARTM2-02 POBR.R'),
                    ('M_206_PRNO', 'Меркурий 206 PRNO'),
                ],
                default='M_234_ART_02_POR',
                max_length=255,
                verbose_name='Модель счетчика',
            ),
        ),
    ]
