# Generated by Django 4.2.5 on 2023-12-11 09:16

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0029_alter_parkingspace_meter_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_penalty',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                max_digits=19,
                verbose_name='Штраф за простой',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='penalty_seconds',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                editable=False,
                max_digits=19,
                verbose_name='Время штрафного простоя',
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='is_reed_installed',
            field=models.BooleanField(
                default=True,
                verbose_name='Пистолет вставлен на место',
            ),
        ),
    ]
