# Generated by Django 4.2.5 on 2024-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0030_order_cost_penalty_order_penalty_seconds_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={
                'ordering': ('pk',),
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='price_kw',
            field=models.DecimalField(
                choices=[
                    (16.0, 'Tesla US 16р. 1 Квт.'),
                    (15.0, 'IEC 62196 15р. 1 Квт.'),
                    (14.0, 'J1772 14р. 1 Квт.'),
                    (15.0, 'GB/T (AC) 15р. 1 Квт.'),
                ],
                decimal_places=2,
                max_digits=10,
                verbose_name='Цена за кВт',
            ),
        ),
    ]
