# Generated by Django 4.2.5 on 2024-02-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0031_alter_parking_space_add_choices_for_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspaceconnector',
            name='connector_type',
            field=models.CharField(
                choices=[
                    ('IEC_62196', 'IEC 62196'),
                    ('J1772', 'J1772'),
                    ('TES_US', 'Tesla Us'),
                    ('GB_T_AC', 'GB/T (AC)'),
                ],
                max_length=20,
                verbose_name='Тип разъема',
            ),
        ),
    ]
