# Generated by Django 4.2.5 on 2024-02-05 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0032_add_new_connector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='reed_install_time',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 5, 11, 9, 46, 818388, tzinfo=datetime.timezone.utc
                ),
                verbose_name='Время, когда был вставлен пистолет',
            ),
        ),
    ]
