# Generated by Django 4.2.5 on 2024-02-05 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0033_add_reed_install_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='reed_install_time',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Время, когда был вставлен пистолет',
            ),
        ),
    ]
