# Generated by Django 4.2.5 on 2024-04-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0034_fix_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='park_lock_serial_number',
            field=models.CharField(
                blank=True, null=True, verbose_name='Серийный номер парклока'
            ),
        ),
    ]
