# Generated by Django 4.2.5 on 2024-05-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0035_add_park_lock_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='park_lock_close_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='Номер пина для закрытия парклока'
            ),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='park_lock_open_pin_number',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='Номер пина для открытия парклока'
            ),
        ),
    ]
