# Generated by Django 4.2.5 on 2024-05-16 12:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0036_add_parklock_open_close_pins'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='idle_amperage_threshold',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('15'),
                max_digits=10,
                verbose_name='Пороговое значение напряжения для начисления простоя',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('ACT', 'Активен'),
                    ('NOM', 'Без оплаты'),
                    ('FIN', 'Завершен'),
                    ('PAR', 'Простой'),
                ],
                max_length=5,
                verbose_name='Статус',
            ),
        ),
    ]
