# Generated by Django 4.2.5 on 2024-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0037_add_idle_amperage_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('ACT', 'Активен'),
                    ('NOM', 'Без оплаты'),
                    ('FIN', 'Завершен'),
                    ('PAR', 'Простой'),
                    ('FPR', 'Простой завершен'),
                ],
                max_length=5,
                verbose_name='Статус',
            ),
        ),
    ]
