# Generated by Django 4.2.5 on 2024-05-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0038_update_statuses_for_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='is_on',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='last_active_status',
            field=models.CharField(
                choices=[
                    ('AV', 'Свободно'),
                    ('BU', 'Занято'),
                    ('CH', 'Заряжается'),
                    ('DI', 'Отключено'),
                    ('BO', 'Забронировано'),
                ],
                default='AV',
                editable=False,
                max_length=5,
                verbose_name='Последний активный статус',
            ),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(
                choices=[
                    ('AV', 'Свободно'),
                    ('BU', 'Занято'),
                    ('CH', 'Заряжается'),
                    ('DI', 'Отключено'),
                    ('BO', 'Забронировано'),
                ],
                max_length=5,
                verbose_name='Статус',
            ),
        ),
        migrations.AlterField(
            model_name='parkingspacestat',
            name='status',
            field=models.CharField(
                choices=[
                    ('AV', 'Свободно'),
                    ('BU', 'Занято'),
                    ('CH', 'Заряжается'),
                    ('DI', 'Отключено'),
                    ('BO', 'Забронировано'),
                ],
                max_length=5,
                verbose_name='Статус',
            ),
        ),
    ]
