# Generated by Django 4.2.16 on 2024-10-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0039_add_last_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssend',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст'),
        ),
    ]
