# Generated by Django 4.2.16 on 2024-10-25 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0040_alter_smssend_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='price_kw',
            field=models.DecimalField(
                choices=[
                    (Decimal('16.00'), 'Tesla US 16р. 1 Квт.'),
                    (Decimal('1500.00'), 'IEC 62196 1500р. 1 Квт.'),
                    (Decimal('14.00'), 'J1772 14р. 1 Квт.'),
                    (Decimal('15.00'), 'GB/T (AC) 15р. 1 Квт.'),
                ],
                decimal_places=2,
                max_digits=10,
                verbose_name='Цена за кВт',
            ),
        ),
    ]
