# Generated by Django 4.2.16 on 2024-10-28 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0041_alter_parkingspace_price_kw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_penalty',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                max_digits=19,
                verbose_name='Двойной штраф за простой',
            ),
        ),
    ]
