# Generated by Django 4.2.5 on 2024-11-11 12:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0042_alter_order_cost_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_kw',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal('0'),
                max_digits=19,
                verbose_name='Конечная накопленная энергия',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_kw',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal('0'),
                max_digits=19,
                verbose_name='Последняя обработанная накопленная энергия',
            ),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='price_kw',
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name='Цена за кВт'
            ),
        ),
    ]
