# Generated by Django 4.2.5 on 2024-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0043_alter_order_end_kw_alter_order_last_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_kw',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=19,
                null=True,
                verbose_name='Конечная накопленная энергия',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_kw',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=19,
                null=True,
                verbose_name='Последняя обработанная накопленная энергия',
            ),
        ),
    ]
