# Generated by Django 4.2.5 on 2024-11-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0044_alter_order_end_kw_alter_order_last_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
