[program:config-loop]
environment=PYTHONPATH=/app
directory=/app
command=python /app/py_scripts/config_loop.py
autorestart=true
priority=100

stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true