# Generated by Django 4.2.2 on 2023-08-10 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'invoice_id',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=50,
                        verbose_name='ID счета в Paykeeper',
                    ),
                ),
                (
                    'invoice_url',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='URL для оплаты',
                    ),
                ),
                (
                    'pay_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=19,
                        verbose_name='Размер платежа',
                    ),
                ),
                (
                    'processing_status',
                    models.CharField(
                        choices=[
                            ('CREATED', 'Создан'),
                            ('PENDING_LINK', 'Ожидание ссылки'),
                            ('PENDING_WEBHOOK', 'Ожидание вебхука'),
                            ('SUCCESS', 'Успех'),
                            ('CANCELLED', 'Отменен'),
                            ('FAILED_LINK', 'Ошибка получения ссылки'),
                            ('FAILED_WEBHOOK', 'Ошибка вебхука'),
                            ('FAILED', 'Ошибка'),
                        ],
                        max_length=20,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Время создания',
                    ),
                ),
                ('expire_at', models.DateTimeField(verbose_name='Дата просрочивания')),
                (
                    'paid_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Время активации',
                    ),
                ),
                (
                    'canceled_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Время отмены',
                    ),
                ),
                (
                    'refunded_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Время возврата денег',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='payments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaykeeperApiLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('API_CALL', 'API запрос'), ('WEBHOOK', 'Вебхук')],
                        max_length=25,
                        verbose_name='Тип',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Обрабатывается'),
                            ('SUCCESS', 'Успех'),
                            ('FAILED', 'Ошибка'),
                            ('IGNORED', 'Проигнорирован'),
                        ],
                        max_length=25,
                        verbose_name='Статус запроса',
                    ),
                ),
                (
                    'url',
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name='URL запроса к Paykeeper',
                    ),
                ),
                (
                    'request',
                    models.JSONField(
                        null=True,
                        verbose_name='Тело запроса к Paykeeper',
                    ),
                ),
                (
                    'response',
                    models.JSONField(
                        null=True,
                        verbose_name='Тело ответа от Paykeeper',
                    ),
                ),
                (
                    'response_status',
                    models.IntegerField(
                        null=True,
                        verbose_name='Статус ответа от Paykeeper',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Время создания',
                    ),
                ),
                (
                    'payment',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='logs',
                        to='payments.payment',
                        verbose_name='Платеж',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paykeeper API лог',
                'verbose_name_plural': 'Paykeeper API лог',
                'ordering': ('-pk',),
            },
        ),
    ]
