# Generated by Django 4.2.2 on 2023-08-10 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0022_city_latitude_city_longitude_city_map_zoom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'kind',
                    models.CharField(
                        choices=[('CREDIT', 'Списание'), ('DEBIT', 'Пополнение')],
                        max_length=32,
                        verbose_name='Тип',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('PAYMENT', 'Пополнение счета картой'),
                            ('BONUS', 'Пополнение счёт бонусами'),
                            ('ORDER', 'Оплата заказа'),
                            ('REFUND', 'Возврат средств'),
                            ('CANCEL_ORDER', 'Отмена оплаты'),
                        ],
                        max_length=32,
                        verbose_name='Действие',
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Сумма',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
                ),
                (
                    'order',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='operations',
                        to='main.order',
                    ),
                ),
                (
                    'payment',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='operations',
                        to='payments.payment',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='operations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('-created_at',),
            },
        ),
    ]
