# Generated by Django 4.2.2 on 2023-08-22 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0024_alter_parkingspace_status_and_more'),
        ('payments', '0003_bonusoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='booking',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='operations',
                to='main.booking',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='action',
            field=models.CharField(
                choices=[
                    ('PAYMENT', 'Пополнение счета картой'),
                    ('BONUS', 'Пополнение счёт бонусами'),
                    ('BOOKING', 'Бронирование'),
                    ('ORDER', 'Оплата заказа'),
                    ('REFUND', 'Возврат средств'),
                    ('CANCEL_ORDER', 'Отмена оплаты'),
                ],
                max_length=32,
                verbose_name='Действие',
            ),
        ),
    ]
