# Generated by Django 4.2.2 on 2023-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0004_operation_booking_alter_operation_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusoperation',
            name='source',
            field=models.CharField(
                default='MANUAL',
                max_length=32,
                verbose_name='За что',
            ),
        ),
    ]
