# Generated by Django 4.2.5 on 2023-09-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0005_bonusoperation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paykeeperapilog',
            name='url',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='URL запроса к Paykeeper',
            ),
        ),
    ]
