# Generated by Django 4.2.5 on 2023-09-12 12:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0006_alter_paykeeperapilog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='paykeeperapilog',
            name='request',
            field=models.TextField(
                blank=True,
                default='',
                verbose_name='Тело запроса к Paykeeper',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paykeeperapilog',
            name='response',
            field=models.TextField(
                blank=True,
                default='',
                verbose_name='Тело ответа от Paykeeper',
            ),
            preserve_default=False,
        ),
    ]
