# Generated by Django 4.2.5 on 2023-09-12 12:54

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    for row in Payment.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_payment_uuid_alter_paykeeperapilog_request_and_more"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
