# Generated by Django 4.2.5 on 2023-09-12 12:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0008_gen_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                null=False,
                unique=True,
                editable=False,
            ),
        ),
    ]
