# Generated by Django 4.2.5 on 2023-09-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0009_alter_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusoperation',
            name='source',
            field=models.CharField(
                choices=[
                    ('MANUAL', 'Добавлен админом'),
                    ('SIGN_UP', 'Стартовый бонус'),
                    ('FILL_PROFILE', 'Бонус заполнения профиля'),
                ],
                default='MANUAL',
                max_length=32,
                verbose_name='За что',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='action',
            field=models.CharField(
                choices=[
                    ('PAYMENT', 'Пополнение счета картой'),
                    ('BONUS', 'Пополнение счёт бонусами'),
                    ('BOOKING', 'Бронирование'),
                    ('ORDER', 'Оплата заказа'),
                    ('REFUND', 'Возврат средств'),
                    ('CANCEL_ORDER', 'Отмена оплаты'),
                ],
                max_length=16,
                verbose_name='Действие',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(
                choices=[('CREDIT', 'Списание'), ('DEBIT', 'Пополнение')],
                max_length=6,
                verbose_name='Тип',
            ),
        ),
    ]
