# Generated by Django 4.2.5 on 2024-01-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            'payments',
            '0010_alter_bonusoperation_source_alter_operation_action_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentApiLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('API_CALL', 'API запрос'), ('WEBHOOK', 'Вебхук')],
                        max_length=25,
                        verbose_name='Тип',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Обрабатывается'),
                            ('SUCCESS', 'Успех'),
                            ('FAILED', 'Ошибка'),
                            ('IGNORED', 'Проигнорирован'),
                        ],
                        max_length=25,
                        verbose_name='Статус запроса',
                    ),
                ),
                (
                    'url',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='URL запроса к платежному серверу',
                    ),
                ),
                (
                    'request',
                    models.TextField(
                        blank=True, verbose_name='Тело запроса к платежному серверу'
                    ),
                ),
                (
                    'response',
                    models.TextField(
                        blank=True, verbose_name='Тело ответа от платежного сервера'
                    ),
                ),
                (
                    'response_status',
                    models.IntegerField(
                        null=True, verbose_name='Статус ответа от платежного сервера'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Время создания'
                    ),
                ),
            ],
            options={
                'verbose_name': 'API лог платежей',
                'verbose_name_plural': 'API лог платежей',
                'ordering': ('-pk',),
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(
                blank=True,
                default='',
                max_length=50,
                verbose_name='ID счета в платежном сервере',
            ),
        ),
        migrations.DeleteModel(
            name='PaykeeperApiLog',
        ),
        migrations.AddField(
            model_name='paymentapilog',
            name='payment',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='logs',
                to='payments.payment',
                verbose_name='Платеж',
            ),
        ),
    ]
