# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
[[outputs.influxdb_v2]]
  urls = ["http://stats.eco-nrg.store:8086"]
  ## Token for authentication.
  token = "l0EO9_kC5ou7muoBwFzdhjGWisQQDBgOJ6b89u4_nb13OrinqPF8GZAqgD-ZT0wu7GP9LnyKVf-GgfdVKXrvBg=="
  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "eco-nrg"
  ## Destination bucket to write into.
  bucket = "rasp-pi"
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = false
[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  # mount_points = ["/"]
  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.mem]]
[[inputs.net]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.temp]]

[[inputs.exec]]
  name_override = "station_state"
  commands = ["/bin/sh -c 'export PYTHONPATH=\"/home/raspi/python/station/\" && /home/raspi/python/station/venv/bin/python3 /home/raspi/python/station/py_scripts/telegraf_redis.py'"]
  data_format = "json_v2"

 [[inputs.exec.json_v2]]
    [[inputs.exec.json_v2.field]]
      # парктрник
      path = "sonic_range_avg"
      type = "float"
    [[inputs.exec.json_v2.field]]
      # парктрник
      path = "sonic_range"
      type = "float"
    [[inputs.exec.json_v2.field]]
      # обновления парктроника
      path = "sonic_last_time"
      type = "uint"
    [[inputs.exec.json_v2.field]]
      # расстояние лидара
      path = "lidar_distance"
      type = "float"
    [[inputs.exec.json_v2.field]]
      # обновления лидара
      path = "lidar_last_time"
      type = "uint"
    [[inputs.exec.json_v2.field]]
      # режим
      path = "state_val"
      type = "int"
    [[inputs.exec.json_v2.field]]
      # статус парклока
      path = "parklock_last_status"
      type = "int"
    [[inputs.exec.json_v2.field]]
      # требуемый статус парклока
      path = "parklock_need_status"
      type = "int"
    [[inputs.exec.json_v2.field]]
      # пистолеты
      path = "reed_value"
      type = "int"
    [[inputs.exec.json_v2.field]]
      # входное питание
      path = "real_has_power"
      type = "int"
    [[inputs.exec.json_v2.field]]
      # реле
      path = "has_power"
      type = "int"
    [[inputs.exec.json_v2.field]]
      # максимальное потребление ампер по фазам
      path = "current_a"
      type = "float"
    [[inputs.exec.json_v2.field]]
      # потребление ампер на 1 фазе
      path = "current_a_phase_1"
      type = "float"
    [[inputs.exec.json_v2.field]]
      # потребление ампер на 2 фазе
      path = "current_a_phase_2"
      type = "float"
    [[inputs.exec.json_v2.field]]
      # потребление ампер на 3 фазе
      path = "current_a_phase_3"
      type = "float"
    [[inputs.exec.json_v2.field]]
      # потребление Ватт
      path = "current_w"
      type = "float"
    [[inputs.exec.json_v2.field]]
      # суммарное потребление киловатты
      path = "total_kw"
      type = "float"
